/**
 * @file test_child_lock_system.c
 * @brief Unit tests for Child Lock System On/Off functionality
 * @author Generated by AI Assistant
 * @date 2026-03-16
 * @version v1.0
 * @details This file contains unit tests for the ChildLockSystem_OnOFF function.
 */

#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "../include/child_lock_system.h"

static void assert_string_equal(const char* expected, const char* actual)
{
    if (expected == NULL) {
        assert(actual == NULL);
    } else {
        assert(actual != NULL);
        assert(strcmp(expected, actual) == 0);
    }
}

static void assert_string_null(const char* actual)
{
    assert(actual == NULL);
}

static void test_speed_greater_than_zero(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 10,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("정차 후 변경 가능", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_crash_detected(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = true,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("사고 감지: 설정 변경 불가 (강제 OFF 우선)", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_power_loss(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = true,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("전원 불안정: 설정 변경 불가", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_acc_off_prevents_change(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_OFF,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("ACC OFF: 설정 변경 불가", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_normal_toggle_off_to_on(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_ON);
    assert(output.setChildLockCommand == true);
    assert(output.updatedChildLockState == CHILD_LOCK_ON);
    assert_string_null(output.displayMessage);
    assert(output.keepCurrentState == false);
}

static void test_normal_toggle_on_to_off(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_ON,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == true);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_null(output.displayMessage);
    assert(output.keepCurrentState == false);
}

static void test_risk_off_without_reconfirm(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_RISK,
        .currentChildLockState = CHILD_LOCK_ON,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_ON);
    assert_string_equal("후석 접근 감지: 재조작시 해제", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_risk_off_with_reconfirm(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_RISK,
        .currentChildLockState = CHILD_LOCK_ON,
        .driverReconfirm = true,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == true);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_null(output.displayMessage);
    assert(output.keepCurrentState == false);
}

static void test_apply_fail(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_FAIL
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_ON);
    assert(output.setChildLockCommand == true);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("설정 실패 (도어 장치 오류)", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_apply_timeout(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = true,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_TIMEOUT
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_ON);
    assert(output.setChildLockCommand == true);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_equal("도어 응답 없음 설정 실패", output.displayMessage);
    assert(output.keepCurrentState == true);
}

static void test_no_toggle_request(void)
{
    ChildLockInput input = {
        .doorId = DOOR_RL,
        .toggleRequest = false,
        .accState = ACC_ON,
        .vehicleSpeed = 0,
        .isCrashDetected = false,
        .isPowerLoss = false,
        .seaStatus = SEA_SAFE,
        .currentChildLockState = CHILD_LOCK_OFF,
        .driverReconfirm = false,
        .applyResult = APPLY_SUCCESS
    };
    ChildLockOutput output;

    ChildLockSystem_OnOFF(&input, &output);

    assert(output.targetChildLockState == CHILD_LOCK_OFF);
    assert(output.setChildLockCommand == false);
    assert(output.updatedChildLockState == CHILD_LOCK_OFF);
    assert_string_null(output.displayMessage);
    assert(output.keepCurrentState == true);
}

int main(void)
{
    const int total_tests = 11;
    int run = 0;

    printf("Running %d unit tests...\n", total_tests);

    test_speed_greater_than_zero(); run++;
    test_crash_detected(); run++;
    test_power_loss(); run++;
    test_acc_off_prevents_change(); run++;
    test_normal_toggle_off_to_on(); run++;
    test_normal_toggle_on_to_off(); run++;
    test_risk_off_without_reconfirm(); run++;
    test_risk_off_with_reconfirm(); run++;
    test_apply_fail(); run++;
    test_apply_timeout(); run++;
    test_no_toggle_request(); run++;




