/**
 * @file child_lock_system.h
 * @brief Header file for Child Lock System On/Off functionality
 * @author Generated by AI Assistant
 * @date 2026-03-16
 * @version v1.0
 * @details This file defines the interfaces and data structures for the Child Lock System On/Off feature.
 */

#ifndef CHILD_LOCK_SYSTEM_H
#define CHILD_LOCK_SYSTEM_H

#include <stdbool.h>
#include <stdint.h>

/**
 * @brief Enumeration for door identification
 */
typedef enum {
    DOOR_RL,    /**< Rear Left door */
    DOOR_RR     /**< Rear Right door */
} DoorId;

/**
 * @brief Enumeration for ACC state
 */
typedef enum {
    ACC_OFF,    /**< ACC is OFF */
    ACC_ON      /**< ACC is ON */
} AccState;

/**
 * @brief Enumeration for SEA status
 */
typedef enum {
    SEA_SAFE,   /**< Safe status */
    SEA_RISK    /**< Risk status */
} SeaStatus;

/**
 * @brief Enumeration for Child Lock state
 */
typedef enum {
    CHILD_LOCK_OFF, /**< Child Lock is OFF */
    CHILD_LOCK_ON   /**< Child Lock is ON */
} ChildLockState;

/**
 * @brief Enumeration for apply result
 */
typedef enum {
    APPLY_SUCCESS,  /**< Application successful */
    APPLY_FAIL,     /**< Application failed */
    APPLY_TIMEOUT   /**< Application timed out */
} ApplyResult;

/**
 * @brief Structure for input parameters
 */
typedef struct {
    DoorId doorId;                      /**< Target door identifier */
    bool toggleRequest;                 /**< Driver's child lock change request */
    AccState accState;                  /**< ACC state */
    uint32_t vehicleSpeed;              /**< Vehicle speed */
    bool isCrashDetected;               /**< Crash detection status */
    bool isPowerLoss;                   /**< Power loss status */
    SeaStatus seaStatus;                /**< SEA status */
    ChildLockState currentChildLockState; /**< Current child lock state */
    bool driverReconfirm;               /**< Driver reconfirmation after warning */
    ApplyResult applyResult;            /**< Door ECU/Actuator apply result */
} ChildLockInput;

/**
 * @brief Structure for output parameters
 */
typedef struct {
    ChildLockState targetChildLockState;    /**< Target child lock state */
    bool setChildLockCommand;               /**< Command to set child lock */
    ChildLockState updatedChildLockState;   /**< Updated child lock state */
    const char* displayMessage;             /**< Message to display on HMI */
    const char* statusUpdate;               /**< Status update for display */
    bool keepCurrentState;                  /**< Flag to keep current state */
    const char* faultStatus;                /**< Fault status information */
} ChildLockOutput;

/**
 * @brief Main function to handle Child Lock On/Off logic
 * @param input Pointer to input parameters
 * @param output Pointer to output parameters
 * @return void
 * @details This function implements the flowchart logic for toggling child lock state.
 * It performs precondition checks, determines target state, handles warnings, and processes apply results.
 */
void ChildLockSystem_OnOFF(const ChildLockInput* input, ChildLockOutput* output);

#endif /* CHILD_LOCK_SYSTEM_H */