/**
 * @file child_lock_system.c
 * @brief Implementation of Child Lock System On/Off functionality
 * @author Generated by AI Assistant
 * @date 2026-03-16
 * @version v1.0
 * @details This file implements the ChildLockSystem_OnOFF function based on the provided flowchart.
 */

#include "../include/child_lock_system.h"

/**
 * @brief Main function to handle Child Lock On/Off logic
 * @param input Pointer to input parameters
 * @param output Pointer to output parameters
 * @return void
 * @details This function implements the flowchart logic for toggling child lock state.
 * It performs precondition checks, determines target state, handles warnings, and processes apply results.
 */
void ChildLockSystem_OnOFF(const ChildLockInput* input, ChildLockOutput* output) {
    /* Initialize output */
    output->targetChildLockState = input->currentChildLockState;
    output->setChildLockCommand = false;
    output->updatedChildLockState = input->currentChildLockState;
    output->displayMessage = NULL;
    output->statusUpdate = NULL;
    output->keepCurrentState = true;
    output->faultStatus = NULL;

    /* Precondition checks */
    if (!input->toggleRequest) {
        /* No toggle request received; keep current state */
        return;
    }

    if (input->accState != ACC_ON) {
        output->displayMessage = "ACC OFF: 설정 변경 불가";
        return;
    }

    if (input->vehicleSpeed > 0) {
        output->displayMessage = "정차 후 변경 가능";
        return;
    }

    if (input->isCrashDetected) {
        output->displayMessage = "사고 감지: 설정 변경 불가 (강제 OFF 우선)";
        return;
    }

    if (input->isPowerLoss) {
        output->displayMessage = "전원 불안정: 설정 변경 불가";
        return;
    }

    /* Determine target state */
    ChildLockState targetState = (input->currentChildLockState == CHILD_LOCK_OFF) ? CHILD_LOCK_ON : CHILD_LOCK_OFF;
    output->targetChildLockState = targetState;

    /* Check for risk condition */
    if (input->seaStatus == SEA_RISK && targetState == CHILD_LOCK_OFF) {
        output->displayMessage = "후석 접근 감지: 재조작시 해제";
        if (!input->driverReconfirm) {
            return; /* Keep current state */
        }
    }

    /* Send command */
    output->setChildLockCommand = true;

    /* Process apply result */
    if (input->applyResult == APPLY_SUCCESS) {
        output->updatedChildLockState = targetState;
        output->keepCurrentState = false;
        /* statusUpdate would be set here */
    } else if (input->applyResult == APPLY_FAIL) {
        output->displayMessage = "설정 실패 (도어 장치 오류)";
        /* Keep current state */
    } else if (input->applyResult == APPLY_TIMEOUT) {
        output->displayMessage = "도어 응답 없음 설정 실패";
        output->faultStatus = "Timeout"; /* Log fault */
        /* Keep current state */
    }
}